#!/usr/bin/env bash
set -euo pipefail

CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/stagecore"
ENV_FILE="$CONFIG_DIR/qualification.env"
mkdir -p "$CONFIG_DIR"
chmod 700 "$CONFIG_DIR"

if [[ ! -f "$ENV_FILE" ]]; then
  cat >"$ENV_FILE" <<'EOF'
# Local-only StageCore physical qualification configuration.
# Never commit this file.
STAGECORE_PI_HOST=
STAGECORE_PI_USER=
STAGECORE_PROJECT_ID=
STAGECORE_RUNTIME_SNAPSHOT_ID=
STAGECORE_TABLET_DEVICE_ID=
STAGECORE_TABLET_BUILD_SHA=
STAGECORE_TABLET_APK_SHA256=
STAGECORE_LIGHTING_NODE_ID=
STAGECORE_LIGHTING_FIRMWARE_SHA=
STAGECORE_HARDWARE_BASELINE_ID=
STAGECORE_TABLET_QUALIFICATION_MEDIA_NUMBER=
STAGECORE_QUALIFICATION_ENABLE_PHYSICAL_ACTIONS=0
STAGECORE_QUALIFICATION_PHYSICAL_HOLD_SECONDS=2
STAGECORE_LIGHTING_QUALIFICATION_CHANNEL_KEY=
STAGECORE_LIGHTING_QUALIFICATION_SET_LEVEL=
STAGECORE_LIGHTING_QUALIFICATION_FADE_LEVEL=
STAGECORE_LIGHTING_QUALIFICATION_FADE_MS=
STAGECORE_LIGHTING_QUALIFICATION_SECOND_CHANNEL_KEY=
STAGECORE_LIGHTING_QUALIFICATION_SECOND_SET_LEVEL=
STAGECORE_LIGHTING_QUALIFICATION_SECOND_FADE_LEVEL=
STAGECORE_LIGHTING_QUALIFICATION_TIMED_BLACKOUT_MS=
EOF
  chmod 600 "$ENV_FILE"
fi

KEY="$CONFIG_DIR/qualification_ed25519"
if [[ ! -f "$KEY" ]]; then
  ssh-keygen -q -t ed25519 -N '' -f "$KEY" -C stagecore-qualification
fi
chmod 600 "$KEY"
chmod 644 "$KEY.pub"

printf 'Qualification config: %s\n' "$ENV_FILE"
printf 'SSH public key: %s.pub\n' "$KEY"
printf '\nNext: fill Pi access and exact candidate identity pins. Device IDs may stay blank only when exactly one matching device exists. Then run tools/qualification/bootstrap-pi-access.sh once.\n'
